name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]  # or the branch you want to trigger on
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io  # Change to ghcr.io if using GitHub Container Registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # Or GHCR_USERNAME
        password: ${{ secrets.DOCKERHUB_TOKEN }}     # Or GHCR_TOKEN

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64  # Specify platforms if needed
        push: true
        tags: your_dockerhub_username/reinvent-community-env:latest  # Adjust accordingly
